# This is a basic workflow to help you get started with Actions

name: livecd_builder

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build livecd
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        LIVECD_PROFILE:
        - aarch64-default

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: master

    # install deps
    - name: Install deps
      shell: bash
      run: |
        sudo apt update -qq
        sudo apt install -y tree rsync openssh-client qemu-user-static

    # Runs a single command using the runners shell
    - name: Run makelivecd script
      shell: bash
      env:
        LIVECD_PROFILE: ${{ matrix.LIVECD_PROFILE }}
      run: sudo LIVECD_PROFILE="$LIVECD_PROFILE" bash makelivecd.sh

    - name: Upload to server
      run: |
        export DATE=$(date +"%Y.%m.%d")
        find root.x86_64 |grep \.iso$
        ls -alh "root.x86_64/livecd/releng/upload/$DATE/archlinuxarm-$DATE-aarch64.iso"
        sshpass -p "${{ secrets.ssh_password }}" scp -o StrictHostKeyChecking=no root.x86_64/livecd/releng/upload/$DATE/archlinuxarm-$DATE-aarch64.iso root@165.22.92.124:/root
